// Identity service gRPC surface (ADR-019). State-mutating RPCs map 1:1 onto
// plane/application/identity.Service methods; the server performs the source
// write + outbox row in a single MetadataStore.Transact (ADR-008).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: gitscale/identity/v1/identity.proto

package identityv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HumanUser is the wire projection of plane/application/identity.HumanUser.
// CredentialHash is intentionally omitted from the wire format — the gRPC
// surface never returns hashes to clients.
type HumanUser struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email          string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	RateBucket     string                 `protobuf:"bytes,3,opt,name=rate_bucket,json=rateBucket,proto3" json:"rate_bucket,omitempty"`
	QuotaAccountId string                 `protobuf:"bytes,4,opt,name=quota_account_id,json=quotaAccountId,proto3" json:"quota_account_id,omitempty"` // empty if NULL
	Disabled       bool                   `protobuf:"varint,5,opt,name=disabled,proto3" json:"disabled,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HumanUser) Reset() {
	*x = HumanUser{}
	mi := &file_gitscale_identity_v1_identity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HumanUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HumanUser) ProtoMessage() {}

func (x *HumanUser) ProtoReflect() protoreflect.Message {
	mi := &file_gitscale_identity_v1_identity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HumanUser.ProtoReflect.Descriptor instead.
func (*HumanUser) Descriptor() ([]byte, []int) {
	return file_gitscale_identity_v1_identity_proto_rawDescGZIP(), []int{0}
}

func (x *HumanUser) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HumanUser) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *HumanUser) GetRateBucket() string {
	if x != nil {
		return x.RateBucket
	}
	return ""
}

func (x *HumanUser) GetQuotaAccountId() string {
	if x != nil {
		return x.QuotaAccountId
	}
	return ""
}

func (x *HumanUser) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

// AgentIdentity is the wire projection of plane/application/identity.AgentIdentity.
type AgentIdentity struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DisplayName     string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	ParentUserId    string                 `protobuf:"bytes,3,opt,name=parent_user_id,json=parentUserId,proto3" json:"parent_user_id,omitempty"`
	PermissionScope []string               `protobuf:"bytes,4,rep,name=permission_scope,json=permissionScope,proto3" json:"permission_scope,omitempty"`
	RateBucket      string                 `protobuf:"bytes,5,opt,name=rate_bucket,json=rateBucket,proto3" json:"rate_bucket,omitempty"`
	ReputationScore float64                `protobuf:"fixed64,6,opt,name=reputation_score,json=reputationScore,proto3" json:"reputation_score,omitempty"`
	QuotaAccountId  string                 `protobuf:"bytes,7,opt,name=quota_account_id,json=quotaAccountId,proto3" json:"quota_account_id,omitempty"` // empty if NULL
	Revoked         bool                   `protobuf:"varint,8,opt,name=revoked,proto3" json:"revoked,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AgentIdentity) Reset() {
	*x = AgentIdentity{}
	mi := &file_gitscale_identity_v1_identity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentIdentity) ProtoMessage() {}

func (x *AgentIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_gitscale_identity_v1_identity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentIdentity.ProtoReflect.Descriptor instead.
func (*AgentIdentity) Descriptor() ([]byte, []int) {
	return file_gitscale_identity_v1_identity_proto_rawDescGZIP(), []int{1}
}

func (x *AgentIdentity) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AgentIdentity) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *AgentIdentity) GetParentUserId() string {
	if x != nil {
		return x.ParentUserId
	}
	return ""
}

func (x *AgentIdentity) GetPermissionScope() []string {
	if x != nil {
		return x.PermissionScope
	}
	return nil
}

func (x *AgentIdentity) GetRateBucket() string {
	if x != nil {
		return x.RateBucket
	}
	return ""
}

func (x *AgentIdentity) GetReputationScore() float64 {
	if x != nil {
		return x.ReputationScore
	}
	return 0
}

func (x *AgentIdentity) GetQuotaAccountId() string {
	if x != nil {
		return x.QuotaAccountId
	}
	return ""
}

func (x *AgentIdentity) GetRevoked() bool {
	if x != nil {
		return x.Revoked
	}
	return false
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_gitscale_identity_v1_identity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gitscale_identity_v1_identity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_gitscale_identity_v1_identity_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	User          *HumanUser             `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_gitscale_identity_v1_identity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gitscale_identity_v1_identity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_gitscale_identity_v1_identity_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetUserResponse) GetUser() *HumanUser {
	if x != nil {
		return x.User
	}
	return nil
}

type GetAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentRequest) Reset() {
	*x = GetAgentRequest{}
	mi := &file_gitscale_identity_v1_identity_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentRequest) ProtoMessage() {}

func (x *GetAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gitscale_identity_v1_identity_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentRequest.ProtoReflect.Descriptor instead.
func (*GetAgentRequest) Descriptor() ([]byte, []int) {
	return file_gitscale_identity_v1_identity_proto_rawDescGZIP(), []int{4}
}

func (x *GetAgentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Agent         *AgentIdentity         `protobuf:"bytes,2,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentResponse) Reset() {
	*x = GetAgentResponse{}
	mi := &file_gitscale_identity_v1_identity_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentResponse) ProtoMessage() {}

func (x *GetAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gitscale_identity_v1_identity_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentResponse.ProtoReflect.Descriptor instead.
func (*GetAgentResponse) Descriptor() ([]byte, []int) {
	return file_gitscale_identity_v1_identity_proto_rawDescGZIP(), []int{5}
}

func (x *GetAgentResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetAgentResponse) GetAgent() *AgentIdentity {
	if x != nil {
		return x.Agent
	}
	return nil
}

type CreateUserRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Email               string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	PlaintextCredential string                 `protobuf:"bytes,2,opt,name=plaintext_credential,json=plaintextCredential,proto3" json:"plaintext_credential,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_gitscale_identity_v1_identity_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gitscale_identity_v1_identity_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_gitscale_identity_v1_identity_proto_rawDescGZIP(), []int{6}
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserRequest) GetPlaintextCredential() string {
	if x != nil {
		return x.PlaintextCredential
	}
	return ""
}

type CreateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *HumanUser             `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_gitscale_identity_v1_identity_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gitscale_identity_v1_identity_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_gitscale_identity_v1_identity_proto_rawDescGZIP(), []int{7}
}

func (x *CreateUserResponse) GetUser() *HumanUser {
	if x != nil {
		return x.User
	}
	return nil
}

type CreateAgentRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ParentUserId    string                 `protobuf:"bytes,1,opt,name=parent_user_id,json=parentUserId,proto3" json:"parent_user_id,omitempty"`
	DisplayName     string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	PermissionScope []string               `protobuf:"bytes,3,rep,name=permission_scope,json=permissionScope,proto3" json:"permission_scope,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateAgentRequest) Reset() {
	*x = CreateAgentRequest{}
	mi := &file_gitscale_identity_v1_identity_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAgentRequest) ProtoMessage() {}

func (x *CreateAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gitscale_identity_v1_identity_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAgentRequest.ProtoReflect.Descriptor instead.
func (*CreateAgentRequest) Descriptor() ([]byte, []int) {
	return file_gitscale_identity_v1_identity_proto_rawDescGZIP(), []int{8}
}

func (x *CreateAgentRequest) GetParentUserId() string {
	if x != nil {
		return x.ParentUserId
	}
	return ""
}

func (x *CreateAgentRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *CreateAgentRequest) GetPermissionScope() []string {
	if x != nil {
		return x.PermissionScope
	}
	return nil
}

type CreateAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         *AgentIdentity         `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAgentResponse) Reset() {
	*x = CreateAgentResponse{}
	mi := &file_gitscale_identity_v1_identity_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAgentResponse) ProtoMessage() {}

func (x *CreateAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gitscale_identity_v1_identity_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAgentResponse.ProtoReflect.Descriptor instead.
func (*CreateAgentResponse) Descriptor() ([]byte, []int) {
	return file_gitscale_identity_v1_identity_proto_rawDescGZIP(), []int{9}
}

func (x *CreateAgentResponse) GetAgent() *AgentIdentity {
	if x != nil {
		return x.Agent
	}
	return nil
}

type DisableUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableUserRequest) Reset() {
	*x = DisableUserRequest{}
	mi := &file_gitscale_identity_v1_identity_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableUserRequest) ProtoMessage() {}

func (x *DisableUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gitscale_identity_v1_identity_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableUserRequest.ProtoReflect.Descriptor instead.
func (*DisableUserRequest) Descriptor() ([]byte, []int) {
	return file_gitscale_identity_v1_identity_proto_rawDescGZIP(), []int{10}
}

func (x *DisableUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DisableUserRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type DisableUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableUserResponse) Reset() {
	*x = DisableUserResponse{}
	mi := &file_gitscale_identity_v1_identity_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableUserResponse) ProtoMessage() {}

func (x *DisableUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gitscale_identity_v1_identity_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableUserResponse.ProtoReflect.Descriptor instead.
func (*DisableUserResponse) Descriptor() ([]byte, []int) {
	return file_gitscale_identity_v1_identity_proto_rawDescGZIP(), []int{11}
}

type RevokeAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeAgentRequest) Reset() {
	*x = RevokeAgentRequest{}
	mi := &file_gitscale_identity_v1_identity_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeAgentRequest) ProtoMessage() {}

func (x *RevokeAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gitscale_identity_v1_identity_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeAgentRequest.ProtoReflect.Descriptor instead.
func (*RevokeAgentRequest) Descriptor() ([]byte, []int) {
	return file_gitscale_identity_v1_identity_proto_rawDescGZIP(), []int{12}
}

func (x *RevokeAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RevokeAgentRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RevokeAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeAgentResponse) Reset() {
	*x = RevokeAgentResponse{}
	mi := &file_gitscale_identity_v1_identity_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeAgentResponse) ProtoMessage() {}

func (x *RevokeAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gitscale_identity_v1_identity_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeAgentResponse.ProtoReflect.Descriptor instead.
func (*RevokeAgentResponse) Descriptor() ([]byte, []int) {
	return file_gitscale_identity_v1_identity_proto_rawDescGZIP(), []int{13}
}

type UpdateAgentPermissionsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AgentId         string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	PermissionScope []string               `protobuf:"bytes,2,rep,name=permission_scope,json=permissionScope,proto3" json:"permission_scope,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateAgentPermissionsRequest) Reset() {
	*x = UpdateAgentPermissionsRequest{}
	mi := &file_gitscale_identity_v1_identity_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAgentPermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAgentPermissionsRequest) ProtoMessage() {}

func (x *UpdateAgentPermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gitscale_identity_v1_identity_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAgentPermissionsRequest.ProtoReflect.Descriptor instead.
func (*UpdateAgentPermissionsRequest) Descriptor() ([]byte, []int) {
	return file_gitscale_identity_v1_identity_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateAgentPermissionsRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *UpdateAgentPermissionsRequest) GetPermissionScope() []string {
	if x != nil {
		return x.PermissionScope
	}
	return nil
}

type UpdateAgentPermissionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAgentPermissionsResponse) Reset() {
	*x = UpdateAgentPermissionsResponse{}
	mi := &file_gitscale_identity_v1_identity_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAgentPermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAgentPermissionsResponse) ProtoMessage() {}

func (x *UpdateAgentPermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gitscale_identity_v1_identity_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAgentPermissionsResponse.ProtoReflect.Descriptor instead.
func (*UpdateAgentPermissionsResponse) Descriptor() ([]byte, []int) {
	return file_gitscale_identity_v1_identity_proto_rawDescGZIP(), []int{15}
}

type AddOrgMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddOrgMemberRequest) Reset() {
	*x = AddOrgMemberRequest{}
	mi := &file_gitscale_identity_v1_identity_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddOrgMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOrgMemberRequest) ProtoMessage() {}

func (x *AddOrgMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gitscale_identity_v1_identity_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOrgMemberRequest.ProtoReflect.Descriptor instead.
func (*AddOrgMemberRequest) Descriptor() ([]byte, []int) {
	return file_gitscale_identity_v1_identity_proto_rawDescGZIP(), []int{16}
}

func (x *AddOrgMemberRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *AddOrgMemberRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddOrgMemberRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type AddOrgMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddOrgMemberResponse) Reset() {
	*x = AddOrgMemberResponse{}
	mi := &file_gitscale_identity_v1_identity_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddOrgMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOrgMemberResponse) ProtoMessage() {}

func (x *AddOrgMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gitscale_identity_v1_identity_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOrgMemberResponse.ProtoReflect.Descriptor instead.
func (*AddOrgMemberResponse) Descriptor() ([]byte, []int) {
	return file_gitscale_identity_v1_identity_proto_rawDescGZIP(), []int{17}
}

type RemoveOrgMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveOrgMemberRequest) Reset() {
	*x = RemoveOrgMemberRequest{}
	mi := &file_gitscale_identity_v1_identity_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveOrgMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveOrgMemberRequest) ProtoMessage() {}

func (x *RemoveOrgMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gitscale_identity_v1_identity_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveOrgMemberRequest.ProtoReflect.Descriptor instead.
func (*RemoveOrgMemberRequest) Descriptor() ([]byte, []int) {
	return file_gitscale_identity_v1_identity_proto_rawDescGZIP(), []int{18}
}

func (x *RemoveOrgMemberRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *RemoveOrgMemberRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type RemoveOrgMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveOrgMemberResponse) Reset() {
	*x = RemoveOrgMemberResponse{}
	mi := &file_gitscale_identity_v1_identity_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveOrgMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveOrgMemberResponse) ProtoMessage() {}

func (x *RemoveOrgMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gitscale_identity_v1_identity_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveOrgMemberResponse.ProtoReflect.Descriptor instead.
func (*RemoveOrgMemberResponse) Descriptor() ([]byte, []int) {
	return file_gitscale_identity_v1_identity_proto_rawDescGZIP(), []int{19}
}

var File_gitscale_identity_v1_identity_proto protoreflect.FileDescriptor

const file_gitscale_identity_v1_identity_proto_rawDesc = "" +
	"\n" +
	"#gitscale/identity/v1/identity.proto\x12\x14gitscale.identity.v1\"\x98\x01\n" +
	"\tHumanUser\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1f\n" +
	"\vrate_bucket\x18\x03 \x01(\tR\n" +
	"rateBucket\x12(\n" +
	"\x10quota_account_id\x18\x04 \x01(\tR\x0equotaAccountId\x12\x1a\n" +
	"\bdisabled\x18\x05 \x01(\bR\bdisabled\"\xa3\x02\n" +
	"\rAgentIdentity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12$\n" +
	"\x0eparent_user_id\x18\x03 \x01(\tR\fparentUserId\x12)\n" +
	"\x10permission_scope\x18\x04 \x03(\tR\x0fpermissionScope\x12\x1f\n" +
	"\vrate_bucket\x18\x05 \x01(\tR\n" +
	"rateBucket\x12)\n" +
	"\x10reputation_score\x18\x06 \x01(\x01R\x0freputationScore\x12(\n" +
	"\x10quota_account_id\x18\a \x01(\tR\x0equotaAccountId\x12\x18\n" +
	"\arevoked\x18\b \x01(\bR\arevoked\" \n" +
	"\x0eGetUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\\\n" +
	"\x0fGetUserResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x123\n" +
	"\x04user\x18\x02 \x01(\v2\x1f.gitscale.identity.v1.HumanUserR\x04user\"!\n" +
	"\x0fGetAgentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"c\n" +
	"\x10GetAgentResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x129\n" +
	"\x05agent\x18\x02 \x01(\v2#.gitscale.identity.v1.AgentIdentityR\x05agent\"\\\n" +
	"\x11CreateUserRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x121\n" +
	"\x14plaintext_credential\x18\x02 \x01(\tR\x13plaintextCredential\"I\n" +
	"\x12CreateUserResponse\x123\n" +
	"\x04user\x18\x01 \x01(\v2\x1f.gitscale.identity.v1.HumanUserR\x04user\"\x88\x01\n" +
	"\x12CreateAgentRequest\x12$\n" +
	"\x0eparent_user_id\x18\x01 \x01(\tR\fparentUserId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12)\n" +
	"\x10permission_scope\x18\x03 \x03(\tR\x0fpermissionScope\"P\n" +
	"\x13CreateAgentResponse\x129\n" +
	"\x05agent\x18\x01 \x01(\v2#.gitscale.identity.v1.AgentIdentityR\x05agent\"E\n" +
	"\x12DisableUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x15\n" +
	"\x13DisableUserResponse\"G\n" +
	"\x12RevokeAgentRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x15\n" +
	"\x13RevokeAgentResponse\"e\n" +
	"\x1dUpdateAgentPermissionsRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12)\n" +
	"\x10permission_scope\x18\x02 \x03(\tR\x0fpermissionScope\" \n" +
	"\x1eUpdateAgentPermissionsResponse\"Y\n" +
	"\x13AddOrgMemberRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\"\x16\n" +
	"\x14AddOrgMemberResponse\"H\n" +
	"\x16RemoveOrgMemberRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\x19\n" +
	"\x17RemoveOrgMemberResponse2\xae\a\n" +
	"\x0fIdentityService\x12V\n" +
	"\aGetUser\x12$.gitscale.identity.v1.GetUserRequest\x1a%.gitscale.identity.v1.GetUserResponse\x12Y\n" +
	"\bGetAgent\x12%.gitscale.identity.v1.GetAgentRequest\x1a&.gitscale.identity.v1.GetAgentResponse\x12_\n" +
	"\n" +
	"CreateUser\x12'.gitscale.identity.v1.CreateUserRequest\x1a(.gitscale.identity.v1.CreateUserResponse\x12b\n" +
	"\vCreateAgent\x12(.gitscale.identity.v1.CreateAgentRequest\x1a).gitscale.identity.v1.CreateAgentResponse\x12b\n" +
	"\vDisableUser\x12(.gitscale.identity.v1.DisableUserRequest\x1a).gitscale.identity.v1.DisableUserResponse\x12b\n" +
	"\vRevokeAgent\x12(.gitscale.identity.v1.RevokeAgentRequest\x1a).gitscale.identity.v1.RevokeAgentResponse\x12\x83\x01\n" +
	"\x16UpdateAgentPermissions\x123.gitscale.identity.v1.UpdateAgentPermissionsRequest\x1a4.gitscale.identity.v1.UpdateAgentPermissionsResponse\x12e\n" +
	"\fAddOrgMember\x12).gitscale.identity.v1.AddOrgMemberRequest\x1a*.gitscale.identity.v1.AddOrgMemberResponse\x12n\n" +
	"\x0fRemoveOrgMember\x12,.gitscale.identity.v1.RemoveOrgMemberRequest\x1a-.gitscale.identity.v1.RemoveOrgMemberResponseB\xe8\x01\n" +
	"\x18com.gitscale.identity.v1B\rIdentityProtoP\x01ZKgithub.com/gitscale-platform/gitscale/internal/proto/identity/v1;identityv1\xa2\x02\x03GIX\xaa\x02\x14Gitscale.Identity.V1\xca\x02\x14Gitscale\\Identity\\V1\xe2\x02 Gitscale\\Identity\\V1\\GPBMetadata\xea\x02\x16Gitscale::Identity::V1b\x06proto3"

var (
	file_gitscale_identity_v1_identity_proto_rawDescOnce sync.Once
	file_gitscale_identity_v1_identity_proto_rawDescData []byte
)

func file_gitscale_identity_v1_identity_proto_rawDescGZIP() []byte {
	file_gitscale_identity_v1_identity_proto_rawDescOnce.Do(func() {
		file_gitscale_identity_v1_identity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gitscale_identity_v1_identity_proto_rawDesc), len(file_gitscale_identity_v1_identity_proto_rawDesc)))
	})
	return file_gitscale_identity_v1_identity_proto_rawDescData
}

var file_gitscale_identity_v1_identity_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_gitscale_identity_v1_identity_proto_goTypes = []any{
	(*HumanUser)(nil),                      // 0: gitscale.identity.v1.HumanUser
	(*AgentIdentity)(nil),                  // 1: gitscale.identity.v1.AgentIdentity
	(*GetUserRequest)(nil),                 // 2: gitscale.identity.v1.GetUserRequest
	(*GetUserResponse)(nil),                // 3: gitscale.identity.v1.GetUserResponse
	(*GetAgentRequest)(nil),                // 4: gitscale.identity.v1.GetAgentRequest
	(*GetAgentResponse)(nil),               // 5: gitscale.identity.v1.GetAgentResponse
	(*CreateUserRequest)(nil),              // 6: gitscale.identity.v1.CreateUserRequest
	(*CreateUserResponse)(nil),             // 7: gitscale.identity.v1.CreateUserResponse
	(*CreateAgentRequest)(nil),             // 8: gitscale.identity.v1.CreateAgentRequest
	(*CreateAgentResponse)(nil),            // 9: gitscale.identity.v1.CreateAgentResponse
	(*DisableUserRequest)(nil),             // 10: gitscale.identity.v1.DisableUserRequest
	(*DisableUserResponse)(nil),            // 11: gitscale.identity.v1.DisableUserResponse
	(*RevokeAgentRequest)(nil),             // 12: gitscale.identity.v1.RevokeAgentRequest
	(*RevokeAgentResponse)(nil),            // 13: gitscale.identity.v1.RevokeAgentResponse
	(*UpdateAgentPermissionsRequest)(nil),  // 14: gitscale.identity.v1.UpdateAgentPermissionsRequest
	(*UpdateAgentPermissionsResponse)(nil), // 15: gitscale.identity.v1.UpdateAgentPermissionsResponse
	(*AddOrgMemberRequest)(nil),            // 16: gitscale.identity.v1.AddOrgMemberRequest
	(*AddOrgMemberResponse)(nil),           // 17: gitscale.identity.v1.AddOrgMemberResponse
	(*RemoveOrgMemberRequest)(nil),         // 18: gitscale.identity.v1.RemoveOrgMemberRequest
	(*RemoveOrgMemberResponse)(nil),        // 19: gitscale.identity.v1.RemoveOrgMemberResponse
}
var file_gitscale_identity_v1_identity_proto_depIdxs = []int32{
	0,  // 0: gitscale.identity.v1.GetUserResponse.user:type_name -> gitscale.identity.v1.HumanUser
	1,  // 1: gitscale.identity.v1.GetAgentResponse.agent:type_name -> gitscale.identity.v1.AgentIdentity
	0,  // 2: gitscale.identity.v1.CreateUserResponse.user:type_name -> gitscale.identity.v1.HumanUser
	1,  // 3: gitscale.identity.v1.CreateAgentResponse.agent:type_name -> gitscale.identity.v1.AgentIdentity
	2,  // 4: gitscale.identity.v1.IdentityService.GetUser:input_type -> gitscale.identity.v1.GetUserRequest
	4,  // 5: gitscale.identity.v1.IdentityService.GetAgent:input_type -> gitscale.identity.v1.GetAgentRequest
	6,  // 6: gitscale.identity.v1.IdentityService.CreateUser:input_type -> gitscale.identity.v1.CreateUserRequest
	8,  // 7: gitscale.identity.v1.IdentityService.CreateAgent:input_type -> gitscale.identity.v1.CreateAgentRequest
	10, // 8: gitscale.identity.v1.IdentityService.DisableUser:input_type -> gitscale.identity.v1.DisableUserRequest
	12, // 9: gitscale.identity.v1.IdentityService.RevokeAgent:input_type -> gitscale.identity.v1.RevokeAgentRequest
	14, // 10: gitscale.identity.v1.IdentityService.UpdateAgentPermissions:input_type -> gitscale.identity.v1.UpdateAgentPermissionsRequest
	16, // 11: gitscale.identity.v1.IdentityService.AddOrgMember:input_type -> gitscale.identity.v1.AddOrgMemberRequest
	18, // 12: gitscale.identity.v1.IdentityService.RemoveOrgMember:input_type -> gitscale.identity.v1.RemoveOrgMemberRequest
	3,  // 13: gitscale.identity.v1.IdentityService.GetUser:output_type -> gitscale.identity.v1.GetUserResponse
	5,  // 14: gitscale.identity.v1.IdentityService.GetAgent:output_type -> gitscale.identity.v1.GetAgentResponse
	7,  // 15: gitscale.identity.v1.IdentityService.CreateUser:output_type -> gitscale.identity.v1.CreateUserResponse
	9,  // 16: gitscale.identity.v1.IdentityService.CreateAgent:output_type -> gitscale.identity.v1.CreateAgentResponse
	11, // 17: gitscale.identity.v1.IdentityService.DisableUser:output_type -> gitscale.identity.v1.DisableUserResponse
	13, // 18: gitscale.identity.v1.IdentityService.RevokeAgent:output_type -> gitscale.identity.v1.RevokeAgentResponse
	15, // 19: gitscale.identity.v1.IdentityService.UpdateAgentPermissions:output_type -> gitscale.identity.v1.UpdateAgentPermissionsResponse
	17, // 20: gitscale.identity.v1.IdentityService.AddOrgMember:output_type -> gitscale.identity.v1.AddOrgMemberResponse
	19, // 21: gitscale.identity.v1.IdentityService.RemoveOrgMember:output_type -> gitscale.identity.v1.RemoveOrgMemberResponse
	13, // [13:22] is the sub-list for method output_type
	4,  // [4:13] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_gitscale_identity_v1_identity_proto_init() }
func file_gitscale_identity_v1_identity_proto_init() {
	if File_gitscale_identity_v1_identity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gitscale_identity_v1_identity_proto_rawDesc), len(file_gitscale_identity_v1_identity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gitscale_identity_v1_identity_proto_goTypes,
		DependencyIndexes: file_gitscale_identity_v1_identity_proto_depIdxs,
		MessageInfos:      file_gitscale_identity_v1_identity_proto_msgTypes,
	}.Build()
	File_gitscale_identity_v1_identity_proto = out.File
	file_gitscale_identity_v1_identity_proto_goTypes = nil
	file_gitscale_identity_v1_identity_proto_depIdxs = nil
}
