// Billing service gRPC surface (ADR-019). RecordPartitionArchived is the only
// RPC at this revision; it maps onto plane/application/billing.Service and
// performs source-row + outbox-row write in a single Tx (ADR-008).

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: gitscale/billing/v1/billing.proto

package billingv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BillingService_RecordPartitionArchived_FullMethodName = "/gitscale.billing.v1.BillingService/RecordPartitionArchived"
)

// BillingServiceClient is the client API for BillingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BillingService is the only state-mutation path into the billing domain
// from outside the application plane (ADR-019).
type BillingServiceClient interface {
	// RecordPartitionArchived persists the archival outcome for a usage_events
	// monthly partition and emits billing.partition_archived to the outbox in
	// the same Tx. Idempotent on (year, month, partition_name).
	RecordPartitionArchived(ctx context.Context, in *RecordPartitionArchivedRequest, opts ...grpc.CallOption) (*RecordPartitionArchivedResponse, error)
}

type billingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBillingServiceClient(cc grpc.ClientConnInterface) BillingServiceClient {
	return &billingServiceClient{cc}
}

func (c *billingServiceClient) RecordPartitionArchived(ctx context.Context, in *RecordPartitionArchivedRequest, opts ...grpc.CallOption) (*RecordPartitionArchivedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordPartitionArchivedResponse)
	err := c.cc.Invoke(ctx, BillingService_RecordPartitionArchived_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BillingServiceServer is the server API for BillingService service.
// All implementations must embed UnimplementedBillingServiceServer
// for forward compatibility.
//
// BillingService is the only state-mutation path into the billing domain
// from outside the application plane (ADR-019).
type BillingServiceServer interface {
	// RecordPartitionArchived persists the archival outcome for a usage_events
	// monthly partition and emits billing.partition_archived to the outbox in
	// the same Tx. Idempotent on (year, month, partition_name).
	RecordPartitionArchived(context.Context, *RecordPartitionArchivedRequest) (*RecordPartitionArchivedResponse, error)
	mustEmbedUnimplementedBillingServiceServer()
}

// UnimplementedBillingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBillingServiceServer struct{}

func (UnimplementedBillingServiceServer) RecordPartitionArchived(context.Context, *RecordPartitionArchivedRequest) (*RecordPartitionArchivedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordPartitionArchived not implemented")
}
func (UnimplementedBillingServiceServer) mustEmbedUnimplementedBillingServiceServer() {}
func (UnimplementedBillingServiceServer) testEmbeddedByValue()                        {}

// UnsafeBillingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BillingServiceServer will
// result in compilation errors.
type UnsafeBillingServiceServer interface {
	mustEmbedUnimplementedBillingServiceServer()
}

func RegisterBillingServiceServer(s grpc.ServiceRegistrar, srv BillingServiceServer) {
	// If the following call panics, it indicates UnimplementedBillingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BillingService_ServiceDesc, srv)
}

func _BillingService_RecordPartitionArchived_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordPartitionArchivedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).RecordPartitionArchived(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_RecordPartitionArchived_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).RecordPartitionArchived(ctx, req.(*RecordPartitionArchivedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BillingService_ServiceDesc is the grpc.ServiceDesc for BillingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BillingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gitscale.billing.v1.BillingService",
	HandlerType: (*BillingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RecordPartitionArchived",
			Handler:    _BillingService_RecordPartitionArchived_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gitscale/billing/v1/billing.proto",
}
