// Billing service gRPC surface (ADR-019). RecordPartitionArchived is the only
// RPC at this revision; it maps onto plane/application/billing.Service and
// performs source-row + outbox-row write in a single Tx (ADR-008).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: gitscale/billing/v1/billing.proto

package billingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecordPartitionArchivedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`                                       // 2026..2100
	Month         int32                  `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"`                                     // 1..12
	PartitionName string                 `protobuf:"bytes,3,opt,name=partition_name,json=partitionName,proto3" json:"partition_name,omitempty"` // e.g. "usage_events_2026_05"
	LakeUri       string                 `protobuf:"bytes,4,opt,name=lake_uri,json=lakeUri,proto3" json:"lake_uri,omitempty"`                   // canonical s3:// URI returned by ObjectStore.Upload
	RowCount      int64                  `protobuf:"varint,5,opt,name=row_count,json=rowCount,proto3" json:"row_count,omitempty"`
	BytesWritten  int64                  `protobuf:"varint,6,opt,name=bytes_written,json=bytesWritten,proto3" json:"bytes_written,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordPartitionArchivedRequest) Reset() {
	*x = RecordPartitionArchivedRequest{}
	mi := &file_gitscale_billing_v1_billing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordPartitionArchivedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordPartitionArchivedRequest) ProtoMessage() {}

func (x *RecordPartitionArchivedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gitscale_billing_v1_billing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordPartitionArchivedRequest.ProtoReflect.Descriptor instead.
func (*RecordPartitionArchivedRequest) Descriptor() ([]byte, []int) {
	return file_gitscale_billing_v1_billing_proto_rawDescGZIP(), []int{0}
}

func (x *RecordPartitionArchivedRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *RecordPartitionArchivedRequest) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *RecordPartitionArchivedRequest) GetPartitionName() string {
	if x != nil {
		return x.PartitionName
	}
	return ""
}

func (x *RecordPartitionArchivedRequest) GetLakeUri() string {
	if x != nil {
		return x.LakeUri
	}
	return ""
}

func (x *RecordPartitionArchivedRequest) GetRowCount() int64 {
	if x != nil {
		return x.RowCount
	}
	return 0
}

func (x *RecordPartitionArchivedRequest) GetBytesWritten() int64 {
	if x != nil {
		return x.BytesWritten
	}
	return 0
}

type RecordPartitionArchivedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArchiveId     string                 `protobuf:"bytes,1,opt,name=archive_id,json=archiveId,proto3" json:"archive_id,omitempty"` // UUID of partition_archives row (new or existing)
	Created       bool                   `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"`                     // false on idempotent retry
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordPartitionArchivedResponse) Reset() {
	*x = RecordPartitionArchivedResponse{}
	mi := &file_gitscale_billing_v1_billing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordPartitionArchivedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordPartitionArchivedResponse) ProtoMessage() {}

func (x *RecordPartitionArchivedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gitscale_billing_v1_billing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordPartitionArchivedResponse.ProtoReflect.Descriptor instead.
func (*RecordPartitionArchivedResponse) Descriptor() ([]byte, []int) {
	return file_gitscale_billing_v1_billing_proto_rawDescGZIP(), []int{1}
}

func (x *RecordPartitionArchivedResponse) GetArchiveId() string {
	if x != nil {
		return x.ArchiveId
	}
	return ""
}

func (x *RecordPartitionArchivedResponse) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

var File_gitscale_billing_v1_billing_proto protoreflect.FileDescriptor

const file_gitscale_billing_v1_billing_proto_rawDesc = "" +
	"\n" +
	"!gitscale/billing/v1/billing.proto\x12\x13gitscale.billing.v1\"\xce\x01\n" +
	"\x1eRecordPartitionArchivedRequest\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\x12\x14\n" +
	"\x05month\x18\x02 \x01(\x05R\x05month\x12%\n" +
	"\x0epartition_name\x18\x03 \x01(\tR\rpartitionName\x12\x19\n" +
	"\blake_uri\x18\x04 \x01(\tR\alakeUri\x12\x1b\n" +
	"\trow_count\x18\x05 \x01(\x03R\browCount\x12#\n" +
	"\rbytes_written\x18\x06 \x01(\x03R\fbytesWritten\"Z\n" +
	"\x1fRecordPartitionArchivedResponse\x12\x1d\n" +
	"\n" +
	"archive_id\x18\x01 \x01(\tR\tarchiveId\x12\x18\n" +
	"\acreated\x18\x02 \x01(\bR\acreated2\x97\x01\n" +
	"\x0eBillingService\x12\x84\x01\n" +
	"\x17RecordPartitionArchived\x123.gitscale.billing.v1.RecordPartitionArchivedRequest\x1a4.gitscale.billing.v1.RecordPartitionArchivedResponseB\xe0\x01\n" +
	"\x17com.gitscale.billing.v1B\fBillingProtoP\x01ZIgithub.com/gitscale-platform/gitscale/internal/proto/billing/v1;billingv1\xa2\x02\x03GBX\xaa\x02\x13Gitscale.Billing.V1\xca\x02\x13Gitscale\\Billing\\V1\xe2\x02\x1fGitscale\\Billing\\V1\\GPBMetadata\xea\x02\x15Gitscale::Billing::V1b\x06proto3"

var (
	file_gitscale_billing_v1_billing_proto_rawDescOnce sync.Once
	file_gitscale_billing_v1_billing_proto_rawDescData []byte
)

func file_gitscale_billing_v1_billing_proto_rawDescGZIP() []byte {
	file_gitscale_billing_v1_billing_proto_rawDescOnce.Do(func() {
		file_gitscale_billing_v1_billing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gitscale_billing_v1_billing_proto_rawDesc), len(file_gitscale_billing_v1_billing_proto_rawDesc)))
	})
	return file_gitscale_billing_v1_billing_proto_rawDescData
}

var file_gitscale_billing_v1_billing_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_gitscale_billing_v1_billing_proto_goTypes = []any{
	(*RecordPartitionArchivedRequest)(nil),  // 0: gitscale.billing.v1.RecordPartitionArchivedRequest
	(*RecordPartitionArchivedResponse)(nil), // 1: gitscale.billing.v1.RecordPartitionArchivedResponse
}
var file_gitscale_billing_v1_billing_proto_depIdxs = []int32{
	0, // 0: gitscale.billing.v1.BillingService.RecordPartitionArchived:input_type -> gitscale.billing.v1.RecordPartitionArchivedRequest
	1, // 1: gitscale.billing.v1.BillingService.RecordPartitionArchived:output_type -> gitscale.billing.v1.RecordPartitionArchivedResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gitscale_billing_v1_billing_proto_init() }
func file_gitscale_billing_v1_billing_proto_init() {
	if File_gitscale_billing_v1_billing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gitscale_billing_v1_billing_proto_rawDesc), len(file_gitscale_billing_v1_billing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gitscale_billing_v1_billing_proto_goTypes,
		DependencyIndexes: file_gitscale_billing_v1_billing_proto_depIdxs,
		MessageInfos:      file_gitscale_billing_v1_billing_proto_msgTypes,
	}.Build()
	File_gitscale_billing_v1_billing_proto = out.File
	file_gitscale_billing_v1_billing_proto_goTypes = nil
	file_gitscale_billing_v1_billing_proto_depIdxs = nil
}
